-- =====================================================
-- Retail Profitability & Pricing Strategy Analysis
-- Analyst: Aqsa Ghulam
-- Tools: SQL Server
-- Dataset: Superstore
-- Objective: Identify drivers of margin compression and
-- simulate pricing policy impact.
-- =====================================================

SELECT
    Row_ID,
    Order_ID,
    CAST(Order_Date AS DATE) AS Order_Date,
    CAST(Ship_Date AS DATE) AS Ship_Date,
    Ship_Mode,
    Customer_ID,
    Customer_Name,
    Segment,
    Country,
    City,
    State,
    Postal_Code,
    Region,
    Product_ID,
    Category,
    Sub_Category,
    Product_Name,
    CAST(Sales AS DECIMAL(18,4)) AS Sales,
    CAST(Quantity AS INT) AS Quantity,
    CAST(Discount AS DECIMAL(5,2)) AS Discount,
    CAST(Profit AS DECIMAL(18,4)) AS Profit
INTO superstore_clean
FROM superstore_raw;

-- Clean and convert raw data types to prepare for analysis.

-- =====================================================
-- 1. Overall KPI Analysis
-- =====================================================
SELECT
    SUM(Sales) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales), 4) AS Profit_Margin
FROM superstore_clean;

--Calculate overall revenue, profit, and profit margin to establish a baseline for business performance.

-- =====================================================
-- 2. Category Performance Analysis
-- =====================================================

SELECT
    Category,
    SUM(Sales) AS Revenue,
    SUM(Profit) AS Profit,
    ROUND(SUM(Profit)/SUM(Sales), 4) AS Margin
FROM superstore_clean
GROUP BY Category
ORDER BY Margin;

-- Compare profitability across product categories to identify underperforming segments.

-- =====================================================
-- 3. Furniture Analysis
-- =====================================================

SELECT
    Discount,
    SUM(Sales) AS Revenue,
    SUM(Profit) AS Profit,
    ROUND(SUM(Profit)/SUM(Sales), 4) AS Margin
FROM superstore_clean
WHERE Category = 'Furniture'
GROUP BY Discount
ORDER BY Discount;

-- Analyze how different discount levels impact Furniture profitability.

-- =====================================================
-- Scenario Modeling: Remove Furniture Discounts >= 30%
-- =====================================================

SELECT
    SUM(Sales) AS Revenue,
    SUM(Profit) AS Profit,
    ROUND(SUM(Profit)/SUM(Sales),4) AS Margin
FROM superstore_clean
WHERE NOT (Category = 'Furniture' AND Discount >= 0.30);

-- Simulate removing high-discount Furniture sales (>=30%) to estimate impact on overall margin.

--5. Profit Loss

SELECT
    SUM(Sales) AS Lost_Revenue,
    SUM(Profit) AS Lost_Profit
FROM superstore_clean
WHERE Category = 'Furniture'
AND Discount >= 0.30;

--  Measure revenue and profit generated by high-discount furniture transactions.